"use client";

import { CalendarClock, CheckCircle2, ChevronRight, ClipboardCheck, FileCheck2, Filter, Mail, MessageCircle, Phone, Search, UserCheck, Users, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";

type Requirement = { id:string; code:string; position:string; project_name?:string|null; location?:string|null; status:string; applications?:number };
type TeamUser = { id:string; name:string; email:string };
type DocumentRow = { name:string; status:string };
type Activity = { id:string; action:string; note?:string|null; details:Record<string,unknown>; created_at:string };
type Candidate = { id:string; name:string; email?:string|null; phone?:string|null; status:string; stage:string; summary?:string; created_at:string; nationality?:string|null; iqama_number?:string|null; years_experience?:number|null; message?:string|null; requirement_id:string; requirement?:Requirement|null; assigned_to_id?:string|null; assigned_to_name?:string|null; internal_notes?:string|null; follow_up_at?:string|null; interview_at?:string|null; documents:DocumentRow[]; activities?:Activity[] };
type Overview = { stages:Record<string,number>; requirements:Requirement[]; users:TeamUser[] };

const stages=["new","under_review","shortlisted","contacted","interview","documents_pending","selected","hired","on_hold","rejected","withdrawn"] as const;
const docStatuses=["not_requested","pending","received","verified","rejected","expired"];
function humanize(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
function localDate(v:string|null|undefined){return v?v.slice(0,16):"";}
function wa(phone?:string|null){return `https://wa.me/${String(phone||"").replace(/\D/g,"")}`;}

export function ApplicationsManager(){
  const [items,setItems]=useState<Candidate[]>([]),[overview,setOverview]=useState<Overview>({stages:{},requirements:[],users:[]}),[busy,setBusy]=useState(true),[selected,setSelected]=useState<string|null>(null);
  const [query,setQuery]=useState(""),[stage,setStage]=useState("all"),[requirement,setRequirement]=useState("all"),[notice,setNotice]=useState("");
  const load=useCallback(()=>{setBusy(true);Promise.all([api<{items:Candidate[]}>('/cms/inbox/applications?limit=100'),api<Overview>('/cms/applications/overview')]).then(([list,stats])=>{setItems(list.items);setOverview(stats);}).catch(e=>setNotice(e instanceof Error?e.message:"Could not load applications.")).finally(()=>setBusy(false));},[]);
  useEffect(load,[load]);
  const visible=useMemo(()=>items.filter(i=>(stage==="all"||i.stage===stage)&&(requirement==="all"||i.requirement_id===requirement)&&`${i.name} ${i.email||""} ${i.phone||""} ${i.requirement?.position||""}`.toLowerCase().includes(query.toLowerCase())),[items,query,stage,requirement]);
  const selectedItem=items.find(i=>i.id===selected)||null;
  const stats=[["New",overview.stages.new||0],["Review",(overview.stages.under_review||0)+(overview.stages.interview||0)+(overview.stages.documents_pending||0)],["Shortlisted",overview.stages.shortlisted||0],["Selected",overview.stages.selected||0],["Hired",overview.stages.hired||0]];
  return <section className="applications-workspace"><header className="page-head"><div><p className="eyebrow">Recruitment pipeline</p><h1>Applications</h1><p>Screen, assign, contact, verify and mobilize every candidate with a complete activity history.</p></div></header>
    <div className="application-stats">{stats.map(([name,value])=><div key={String(name)}><span>{name}</span><b>{value}</b></div>)}</div>
    <div className="panel applications-panel"><div className="application-toolbar"><label className="search-input"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search candidate, phone or position…"/></label><label><Filter size={14}/><select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All pipeline stages</option>{stages.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select></label><label><BriefLabel>Requirement</BriefLabel><select value={requirement} onChange={e=>setRequirement(e.target.value)}><option value="all">All requirements</option>{overview.requirements.map(r=><option value={r.id} key={r.id}>{r.position} ({r.applications})</option>)}</select></label><span>{visible.length} candidates</span></div>{notice&&<div className="workspace-notice">{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
      {busy?<div className="skeleton"><i/><i/><i/></div>:visible.length?<div className="candidate-table"><div className="candidate-table-head"><span>Candidate</span><span>Requirement</span><span>Experience</span><span>Stage</span><span>Owner</span><span/></div>{visible.map(item=><button className="candidate-row" key={item.id} onClick={()=>setSelected(item.id)}><span><i>{item.name.slice(0,2).toUpperCase()}</i><b>{item.name}<small>{item.phone||item.email||"No contact"} · {new Date(item.created_at).toLocaleDateString()}</small></b></span><span><b>{item.requirement?.position||"Requirement"}<small>{item.requirement?.project_name||item.requirement?.code}</small></b></span><span>{item.years_experience!=null?`${item.years_experience} years`:"Not stated"}</span><span><em className={`pipeline-badge ${item.stage}`}>{humanize(item.stage)}</em></span><span>{item.assigned_to_name||"Unassigned"}</span><span><ChevronRight size={16}/></span></button>)}</div>:<div className="empty"><Users size={28}/><p>No applications match this view.</p></div>}
    </div>{selectedItem&&<CandidatePanel candidate={selectedItem} overview={overview} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);load();}}/>}
  </section>;
}

function BriefLabel({children}:{children:string}){return <span className="sr-only">{children}</span>;}

function CandidatePanel({candidate,overview,onClose,onSaved}:{candidate:Candidate;overview:Overview;onClose:()=>void;onSaved:()=>void}){
  const [detail,setDetail]=useState<Candidate|null>(null),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[tab,setTab]=useState<"profile"|"workflow"|"documents"|"timeline">("profile"),[note,setNote]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{api<Candidate>(`/cms/inbox/applications/${candidate.id}`).then(setDetail).catch(e=>setNotice(e instanceof Error?e.message:"Could not load candidate.")).finally(()=>setBusy(false));},[candidate.id]);
  function update<K extends keyof Candidate>(key:K,value:Candidate[K]){setDetail(d=>d?{...d,[key]:value}:d);}
  async function save(){if(!detail)return;setSaving(true);setNotice("");try{await api(`/cms/applications/${detail.id}/workflow`,{method:'PATCH',body:JSON.stringify({stage:detail.stage,internal_notes:detail.internal_notes||null,assigned_to_id:detail.assigned_to_id||null,follow_up_at:detail.follow_up_at||null,interview_at:detail.interview_at||null,documents:detail.documents.filter(d=>d.name),note:note||null})});setNotice("Candidate workflow saved with an activity record.");setNote("");onSaved();}catch(e){setNotice(e instanceof Error?e.message:"Could not save candidate.");}finally{setSaving(false);}}
  const docs=detail?.documents||[];
  return <div className="candidate-panel-backdrop" onMouseDown={onClose}><aside className="candidate-panel" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">Candidate profile</p><h2>{detail?.name||candidate.name}</h2><span className={`pipeline-badge ${detail?.stage||candidate.stage}`}>{humanize(detail?.stage||candidate.stage)}</span></div><button onClick={onClose}><X size={19}/></button></header><nav>{[["profile","Profile",Users],["workflow","Workflow",UserCheck],["documents","Documents",FileCheck2],["timeline","Timeline",CalendarClock]].map(([id,name,Icon])=><button key={String(id)} className={tab===id?"active":""} onClick={()=>setTab(id as typeof tab)}><Icon size={15}/>{String(name)}</button>)}</nav>{busy||!detail?<div className="candidate-panel-body"><div className="skeleton"><i/><i/></div></div>:<div className="candidate-panel-body">
      {tab==="profile"&&<><section className="candidate-hero"><i>{detail.name.slice(0,2).toUpperCase()}</i><div><h3>{detail.name}</h3><p>{detail.requirement?.position} · {detail.requirement?.project_name}</p><div>{detail.phone&&<a href={`tel:${detail.phone}`}><Phone size={14}/>Call</a>}{detail.phone&&<a href={wa(detail.phone)} target="_blank" rel="noreferrer"><MessageCircle size={14}/>WhatsApp</a>}{detail.email&&<a href={`mailto:${detail.email}`}><Mail size={14}/>Email</a>}</div></div></section><section className="candidate-info-grid"><div><span>Phone</span><b>{detail.phone||"—"}</b></div><div><span>Email</span><b>{detail.email||"—"}</b></div><div><span>Experience</span><b>{detail.years_experience!=null?`${detail.years_experience} years`:"—"}</b></div><div><span>Iqama / ID</span><b>{detail.iqama_number||"—"}</b></div><div><span>Applied</span><b>{new Date(detail.created_at).toLocaleString()}</b></div><div><span>Location</span><b>{detail.requirement?.location||"—"}</b></div></section>{detail.message&&<section className="candidate-message"><span>Candidate message</span><p>{detail.message}</p></section>}</>}
      {tab==="workflow"&&<><label>Pipeline stage<select value={detail.stage} onChange={e=>update("stage",e.target.value)}>{stages.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select></label><label>Assigned recruiter<select value={detail.assigned_to_id||""} onChange={e=>update("assigned_to_id",e.target.value||null)}><option value="">Unassigned</option>{overview.users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><div className="candidate-two-cols"><label>Follow-up<input type="datetime-local" value={localDate(detail.follow_up_at)} onChange={e=>update("follow_up_at",e.target.value||null)}/></label><label>Interview / trade test<input type="datetime-local" value={localDate(detail.interview_at)} onChange={e=>update("interview_at",e.target.value||null)}/></label></div><label>Team-only master notes<textarea rows={5} value={detail.internal_notes||""} onChange={e=>update("internal_notes",e.target.value)} placeholder="Screening result, availability, salary expectations…"/></label><label>Activity note for this update<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="What changed or what should happen next?"/></label></>}
      {tab==="documents"&&<><div className="candidate-section-head"><div><h3>Document & compliance checklist</h3><p>Track readiness before selection and mobilization.</p></div><button onClick={()=>update("documents",[...docs,{name:"",status:"pending"}])}>+ Add document</button></div><div className="document-checklist">{docs.map((doc,i)=><div key={i}><input value={doc.name} onChange={e=>{const rows=[...docs];rows[i]={...doc,name:e.target.value};update("documents",rows);}} placeholder="Passport / CV / Certificate"/><select value={doc.status} onChange={e=>{const rows=[...docs];rows[i]={...doc,status:e.target.value};update("documents",rows);}}>{docStatuses.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select><button onClick={()=>update("documents",docs.filter((_,index)=>index!==i))}><X size={15}/></button></div>)}</div>{!docs.length&&<div className="empty compact"><ClipboardCheck size={24}/><p>No document checklist yet.</p></div>}</>}
      {tab==="timeline"&&<div className="candidate-timeline">{(detail.activities||[]).map(a=><article key={a.id}><i><CheckCircle2 size={14}/></i><div><b>{humanize(a.action)}</b><small>{new Date(a.created_at).toLocaleString()}</small>{a.note&&<p>{a.note}</p>}</div></article>)}{!detail.activities?.length&&<div className="empty compact"><CalendarClock size={24}/><p>No activity recorded yet.</p></div>}</div>}
    </div>}<footer><p>{notice||"All changes are recorded in the candidate timeline."}</p><div><button onClick={onClose}>Close</button><button className="primary-button" disabled={busy||saving} onClick={()=>void save()}>{saving?"Saving…":"Save workflow"}</button></div></footer></aside></div>;
}
