"use client";

import { CalendarClock, CheckCircle2, ChevronRight, ClipboardCheck, Download, FileCheck2, Filter, Mail, MessageCircle, Phone, Search, UserCheck, Users, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";

type Requirement = { id:string; code:string; position:string; project_name?:string|null; location?:string|null; status:string; applications?:number };
type TeamUser = { id:string; name:string; email:string };
type DocumentRow = { name:string; status:string };
type Activity = { id:string; action:string; note?:string|null; details:Record<string,unknown>; created_at:string };
type OperationalStatus = "pending"|"confirmed"|"completed"|"cancelled";
type Candidate = { id:string; name:string; email?:string|null; phone?:string|null; status:string; stage:string; operational_status:OperationalStatus; notification_status:string; notification_requested_at?:string|null; summary?:string; created_at:string; nationality?:string|null; iqama_number?:string|null; years_experience?:number|null; message?:string|null; requirement_id:string; requirement?:Requirement|null; assigned_to_id?:string|null; assigned_to_name?:string|null; internal_notes?:string|null; follow_up_at?:string|null; interview_at?:string|null; documents:DocumentRow[]; activities?:Activity[] };
type Overview = { stages:Record<string,number>; operational:Record<string,number>; requirements:Requirement[]; users:TeamUser[] };

const stages=["new","under_review","shortlisted","contacted","interview","documents_pending","selected","hired","on_hold","rejected","withdrawn"] as const;
const docStatuses=["not_requested","pending","received","verified","rejected","expired"];
const operationalStatuses:OperationalStatus[]=["pending","confirmed","completed","cancelled"];
function humanize(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());}
function localDate(v:string|null|undefined){return v?v.slice(0,16):"";}
function wa(phone?:string|null){return `https://wa.me/${String(phone||"").replace(/\D/g,"")}`;}

export function ApplicationsManager(){
  const [items,setItems]=useState<Candidate[]>([]),[overview,setOverview]=useState<Overview>({stages:{},operational:{},requirements:[],users:[]}),[busy,setBusy]=useState(true),[selected,setSelected]=useState<string|null>(null),[statusBusy,setStatusBusy]=useState<string|null>(null);
  const [query,setQuery]=useState(""),[stage,setStage]=useState("all"),[requirement,setRequirement]=useState("all"),[notice,setNotice]=useState("");
  const load=useCallback(()=>{setBusy(true);Promise.all([api<{items:Candidate[]}>('/cms/inbox/applications?limit=100'),api<Overview>('/cms/applications/overview')]).then(([list,stats])=>{setItems(list.items);setOverview(stats);}).catch(e=>setNotice(e instanceof Error?e.message:"Could not load applications.")).finally(()=>setBusy(false));},[]);
  useEffect(load,[load]);
  const visible=useMemo(()=>items.filter(i=>(stage==="all"||i.operational_status===stage)&&(requirement==="all"||i.requirement_id===requirement)&&`${i.name} ${i.email||""} ${i.phone||""} ${i.iqama_number||""} ${i.requirement?.position||""}`.toLowerCase().includes(query.toLowerCase())),[items,query,stage,requirement]);
  const selectedItem=items.find(i=>i.id===selected)||null;
  const stats=[["Total",items.length],["Pending",overview.operational.pending||0],["Confirmed",overview.operational.confirmed||0],["Completed",overview.operational.completed||0],["Cancelled",overview.operational.cancelled||0]];
  async function changeStatus(item:Candidate,status:OperationalStatus){if(status===item.operational_status)return;setStatusBusy(item.id);setNotice("");try{const result=await api<{status:OperationalStatus;stage:string;notification_status:string;notification_requested_at:string|null}>(`/cms/applications/${item.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setItems(current=>current.map(row=>row.id===item.id?{...row,operational_status:result.status,stage:result.stage,notification_status:result.notification_status,notification_requested_at:result.notification_requested_at}:row));setOverview(current=>({...current,operational:{...current.operational,[item.operational_status]:Math.max(0,(current.operational[item.operational_status]||0)-1),[status]:(current.operational[status]||0)+1}}));setNotice(status==="confirmed"?"Applicant confirmed. SMS/email confirmation is recorded and awaiting the notification integration.":`Application marked ${humanize(status)}.`);}catch(e){setNotice(e instanceof Error?e.message:"Could not update status.");}finally{setStatusBusy(null);}}
  function exportCsv(){const quote=(value:unknown)=>`"${String(value??"").replaceAll('"','""')}"`;const rows=[["SL","Name","Phone / WhatsApp","Email","Iqama","Experience","Short note","Status","Notified","Requirement","Applied"],...visible.map((i,index)=>[index+1,i.name,i.phone,i.email,i.iqama_number,i.years_experience,i.message,i.operational_status,i.notification_status,i.requirement?.position,i.created_at])];const blob=new Blob([rows.map(row=>row.map(quote).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`novarise-applications-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);}
  return <section className="applications-workspace"><header className="page-head"><div><p className="eyebrow">Recruitment pipeline</p><h1>Applications</h1><p>Screen, assign, contact, verify and mobilize every candidate with a complete activity history.</p></div></header>
    <div className="application-stats">{stats.map(([name,value])=><div key={String(name)}><span>{name}</span><b>{value}</b></div>)}</div>
    <div className="panel applications-panel"><div className="application-toolbar"><label className="search-input"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone, Iqama or position…"/></label><label><Filter size={14}/><select value={stage} onChange={e=>setStage(e.target.value)}><option value="all">All statuses</option>{operationalStatuses.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select></label><label><BriefLabel>Requirement</BriefLabel><select value={requirement} onChange={e=>setRequirement(e.target.value)}><option value="all">All requirements</option>{overview.requirements.map(r=><option value={r.id} key={r.id}>{r.position} ({r.applications})</option>)}</select></label><button className="application-export" onClick={exportCsv} disabled={!visible.length}><Download size={14}/> Export CSV</button><span>{visible.length} applications</span></div>{notice&&<div className="workspace-notice">{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
      {busy?<div className="skeleton"><i/><i/><i/></div>:visible.length?<div className="candidate-table operational-table"><div className="candidate-table-head"><span>SL</span><span>Name</span><span>Phone / WhatsApp</span><span>Email</span><span>Iqama</span><span>Experience</span><span>Short note</span><span>Status</span><span>Notified</span><span/></div>{visible.map((item,index)=><div className="candidate-row" key={item.id} onClick={()=>setSelected(item.id)} role="button" tabIndex={0} onKeyDown={e=>e.key==="Enter"&&setSelected(item.id)}><span>{String(index+1).padStart(2,"0")}</span><span className="candidate-name"><i>{item.name.slice(0,2).toUpperCase()}</i><b>{item.name}<small>{item.requirement?.position||"Requirement"}</small></b></span><span className="candidate-contact"><a href={`tel:${item.phone||""}`} onClick={e=>e.stopPropagation()}><Phone size={13}/>{item.phone||"—"}</a>{item.phone&&<a className="whatsapp-link" href={wa(item.phone)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}><MessageCircle size={13}/>WhatsApp</a>}</span><span className="truncate-cell">{item.email||"—"}</span><span>{item.iqama_number||"—"}</span><span>{item.years_experience!=null?`${item.years_experience} years`:"—"}</span><span className="short-note" title={item.message||""}>{item.message||"—"}</span><span><select className={`operational-select ${item.operational_status}`} value={item.operational_status} disabled={statusBusy===item.id} onClick={e=>e.stopPropagation()} onChange={e=>void changeStatus(item,e.target.value as OperationalStatus)}>{operationalStatuses.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select></span><span><em className={`notification-state ${item.notification_status}`}>{item.notification_status==="awaiting_integration"?"Queued":item.notification_status==="sent"?"Sent":"—"}</em></span><span><ChevronRight size={16}/></span></div>)}</div>:<div className="empty"><Users size={28}/><p>No applications match this view.</p></div>}
    </div>{selectedItem&&<CandidatePanel candidate={selectedItem} overview={overview} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);load();}}/>}
  </section>;
}

function BriefLabel({children}:{children:string}){return <span className="sr-only">{children}</span>;}

function CandidatePanel({candidate,overview,onClose,onSaved}:{candidate:Candidate;overview:Overview;onClose:()=>void;onSaved:()=>void}){
  const [detail,setDetail]=useState<Candidate|null>(null),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[tab,setTab]=useState<"profile"|"workflow"|"documents"|"timeline">("profile"),[note,setNote]=useState(""),[notice,setNotice]=useState("");
  useEffect(()=>{api<Candidate>(`/cms/inbox/applications/${candidate.id}`).then(setDetail).catch(e=>setNotice(e instanceof Error?e.message:"Could not load candidate.")).finally(()=>setBusy(false));},[candidate.id]);
  function update<K extends keyof Candidate>(key:K,value:Candidate[K]){setDetail(d=>d?{...d,[key]:value}:d);}
  async function save(){if(!detail)return;setSaving(true);setNotice("");try{await api(`/cms/applications/${detail.id}/workflow`,{method:'PATCH',body:JSON.stringify({stage:detail.stage,internal_notes:detail.internal_notes||null,assigned_to_id:detail.assigned_to_id||null,follow_up_at:detail.follow_up_at||null,interview_at:detail.interview_at||null,documents:detail.documents.filter(d=>d.name),note:note||null})});setNotice("Candidate workflow saved with an activity record.");setNote("");onSaved();}catch(e){setNotice(e instanceof Error?e.message:"Could not save candidate.");}finally{setSaving(false);}}
  const docs=detail?.documents||[];
  return <div className="candidate-panel-backdrop" onMouseDown={onClose}><aside className="candidate-panel" onMouseDown={e=>e.stopPropagation()}><header><div><p className="eyebrow">Candidate profile</p><h2>{detail?.name||candidate.name}</h2><span className={`pipeline-badge ${detail?.stage||candidate.stage}`}>{humanize(detail?.stage||candidate.stage)}</span></div><button onClick={onClose}><X size={19}/></button></header><nav>{[["profile","Profile",Users],["workflow","Workflow",UserCheck],["documents","Documents",FileCheck2],["timeline","Timeline",CalendarClock]].map(([id,name,Icon])=><button key={String(id)} className={tab===id?"active":""} onClick={()=>setTab(id as typeof tab)}><Icon size={15}/>{String(name)}</button>)}</nav>{busy||!detail?<div className="candidate-panel-body"><div className="skeleton"><i/><i/></div></div>:<div className="candidate-panel-body">
      {tab==="profile"&&<><section className="candidate-hero"><i>{detail.name.slice(0,2).toUpperCase()}</i><div><h3>{detail.name}</h3><p>{detail.requirement?.position} · {detail.requirement?.project_name}</p><div>{detail.phone&&<a href={`tel:${detail.phone}`}><Phone size={14}/>Call</a>}{detail.phone&&<a href={wa(detail.phone)} target="_blank" rel="noreferrer"><MessageCircle size={14}/>WhatsApp</a>}{detail.email&&<a href={`mailto:${detail.email}`}><Mail size={14}/>Email</a>}</div></div></section><section className="candidate-info-grid"><div><span>Phone</span><b>{detail.phone||"—"}</b></div><div><span>Email</span><b>{detail.email||"—"}</b></div><div><span>Experience</span><b>{detail.years_experience!=null?`${detail.years_experience} years`:"—"}</b></div><div><span>Iqama / ID</span><b>{detail.iqama_number||"—"}</b></div><div><span>Applied</span><b>{new Date(detail.created_at).toLocaleString()}</b></div><div><span>Location</span><b>{detail.requirement?.location||"—"}</b></div></section>{detail.message&&<section className="candidate-message"><span>Candidate message</span><p>{detail.message}</p></section>}</>}
      {tab==="workflow"&&<><label>Pipeline stage<select value={detail.stage} onChange={e=>update("stage",e.target.value)}>{stages.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select></label><label>Assigned recruiter<select value={detail.assigned_to_id||""} onChange={e=>update("assigned_to_id",e.target.value||null)}><option value="">Unassigned</option>{overview.users.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><div className="candidate-two-cols"><label>Follow-up<input type="datetime-local" value={localDate(detail.follow_up_at)} onChange={e=>update("follow_up_at",e.target.value||null)}/></label><label>Interview / trade test<input type="datetime-local" value={localDate(detail.interview_at)} onChange={e=>update("interview_at",e.target.value||null)}/></label></div><label>Team-only master notes<textarea rows={5} value={detail.internal_notes||""} onChange={e=>update("internal_notes",e.target.value)} placeholder="Screening result, availability, salary expectations…"/></label><label>Activity note for this update<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="What changed or what should happen next?"/></label></>}
      {tab==="documents"&&<><div className="candidate-section-head"><div><h3>Document & compliance checklist</h3><p>Track readiness before selection and mobilization.</p></div><button onClick={()=>update("documents",[...docs,{name:"",status:"pending"}])}>+ Add document</button></div><div className="document-checklist">{docs.map((doc,i)=><div key={i}><input value={doc.name} onChange={e=>{const rows=[...docs];rows[i]={...doc,name:e.target.value};update("documents",rows);}} placeholder="Passport / CV / Certificate"/><select value={doc.status} onChange={e=>{const rows=[...docs];rows[i]={...doc,status:e.target.value};update("documents",rows);}}>{docStatuses.map(s=><option value={s} key={s}>{humanize(s)}</option>)}</select><button onClick={()=>update("documents",docs.filter((_,index)=>index!==i))}><X size={15}/></button></div>)}</div>{!docs.length&&<div className="empty compact"><ClipboardCheck size={24}/><p>No document checklist yet.</p></div>}</>}
      {tab==="timeline"&&<div className="candidate-timeline">{(detail.activities||[]).map(a=><article key={a.id}><i><CheckCircle2 size={14}/></i><div><b>{humanize(a.action)}</b><small>{new Date(a.created_at).toLocaleString()}</small>{a.note&&<p>{a.note}</p>}</div></article>)}{!detail.activities?.length&&<div className="empty compact"><CalendarClock size={24}/><p>No activity recorded yet.</p></div>}</div>}
    </div>}<footer><p>{notice||"All changes are recorded in the candidate timeline."}</p><div><button onClick={onClose}>Close</button><button className="primary-button" disabled={busy||saving} onClick={()=>void save()}>{saving?"Saving…":"Save workflow"}</button></div></footer></aside></div>;
}
