"use client";

import { AlertTriangle, BriefcaseBusiness, CalendarClock, Check, CircleDollarSign, FileCheck2, MapPin, Pencil, Phone, Plus, Save, Search, Trash2, Users, X } from "lucide-react";
import { createPortal } from "react-dom";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";

type RequirementItem = { id:string; slug:string; title:string; status:string; summary?:string; updated_at:string; extra:Record<string,unknown> };
type Contact = { display:string; raw:string; whatsapp:boolean };
type Form = { code:string; position:string; status:"draft"|"active"|"urgent"|"closed"; approval:string; description:string; headcount:number; project_name:string; location:string; rate_amount:string|null; rate_currency:string; rate_unit:string; duration:string; salary_cycle:string; food:string; accommodation:string; documents:string[]; contacts:Contact[]; opens_at:string|null; closes_at:string|null };
type EditorResponse = { status:string; has_draft:boolean; data:Form; application_count:number };

const blankDoc = ["", ""];
const blankContact: Contact = { display:"", raw:"", whatsapp:true };
const tabs = [
  ["identity", "Requirement Card", BriefcaseBusiness],
  ["offer", "Workforce + Offer", CircleDollarSign],
  ["apply", "Application Details", FileCheck2],
  ["publish", "Schedule + Visibility", CalendarClock],
] as const;

function slugify(value:string){ return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,""); }
function label(value:string){ return value.replaceAll("_"," ").replace(/\b\w/g, c=>c.toUpperCase()); }
function isoLocal(value:string|null){ return value ? value.slice(0,16) : ""; }

export function RequirementsManager(){
  const [items,setItems]=useState<RequirementItem[]>([]), [busy,setBusy]=useState(true), [query,setQuery]=useState(""), [status,setStatus]=useState("all");
  const [editing,setEditing]=useState<RequirementItem|null>(null), [newOpen,setNewOpen]=useState(false), [target,setTarget]=useState<"active"|"urgent">("active"), [creating,setCreating]=useState(false), [notice,setNotice]=useState("");
  const load=useCallback(()=>{ setBusy(true); api<{items:RequirementItem[]}>('/cms/content/requirements').then(r=>setItems(r.items)).catch(e=>setNotice(e instanceof Error?e.message:"Could not load requirements.")).finally(()=>setBusy(false)); },[]);
  useEffect(load,[load]);
  const visible=useMemo(()=>items.filter(i=>(status==="all"||i.status===status)&&`${i.title} ${i.slug} ${String(i.extra.project_name||"")}`.toLowerCase().includes(query.toLowerCase())),[items,query,status]);
  const counts=useMemo(()=>Object.fromEntries(["draft","active","urgent","closed"].map(s=>[s,items.filter(i=>i.status===s).length])),[items]);
  async function create(){ setCreating(true); setNotice(""); try{ const row=await api<{id:string;code:string;status:string;updated_at:string}>('/cms/requirements',{method:'POST',body:JSON.stringify({target_status:target})}); setNewOpen(false); setEditing({id:row.id,slug:row.code,title:"",status:row.status,updated_at:row.updated_at,extra:{application_count:0}}); load(); }catch(e){setNotice(e instanceof Error?e.message:"Could not create requirement.");}finally{setCreating(false);} }
  async function remove(item:RequirementItem){ const apps=Number(item.extra.application_count||0); if(apps){ setNotice(`${item.title} has ${apps} application${apps===1?"":"s"}. Close it instead so candidate history remains safe.`); return; } if(!confirm(`Delete “${item.title||"this draft"}”? This cannot be undone.`))return; try{await api(`/cms/requirements/${item.id}`,{method:'DELETE'}); load();}catch(e){setNotice(e instanceof Error?e.message:"Could not delete requirement.");} }
  return <section className="requirements-workspace">
    <header className="page-head"><div><p className="eyebrow">Workforce publishing</p><h1>Requirements</h1><p>Create public openings and follow every candidate from the same connected workflow.</p></div><button className="primary-button" onClick={()=>setNewOpen(true)}><Plus size={16}/> New Requirement</button></header>
    <div className="requirement-stats">{[["All",items.length],["Urgent",counts.urgent],["Active",counts.active],["Draft",counts.draft],["Closed",counts.closed]].map(([name,value])=><button key={String(name)} className={status===String(name).toLowerCase()?"active":""} onClick={()=>setStatus(String(name).toLowerCase())}><span>{name}</span><b>{value}</b></button>)}</div>
    <div className="panel requirement-list-panel"><div className="requirement-toolbar"><label className="search-input"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search position, project or code…"/></label><span>{visible.length} requirement{visible.length===1?"":"s"}</span></div>
      {notice&&<div className="workspace-notice">{notice}<button onClick={()=>setNotice("")}><X size={14}/></button></div>}
      {busy?<div className="skeleton"><i/><i/><i/></div>:<div className="requirement-card-grid">{visible.map(item=><article className={`requirement-admin-card ${item.status}`} key={item.id}><div className="requirement-card-head"><span>{item.status==="urgent"&&<AlertTriangle size={13}/>} {label(item.status)}</span><small>{Number(item.extra.application_count||0)} applications</small></div><div className="requirement-card-main"><p>{String(item.extra.project_name||"Project not set")}</p><h3>{item.title||"Untitled requirement"}</h3><div><span><MapPin size={13}/>{String(item.extra.location||"Location pending")}</span><span><Users size={13}/>{String(item.extra.headcount||1)} positions</span></div></div><footer><div><code>{item.slug}</code><small>Updated {new Date(item.updated_at).toLocaleDateString()}</small></div><div><button title="Edit" onClick={()=>setEditing(item)}><Pencil size={15}/></button><button className="danger" title="Delete" onClick={()=>void remove(item)}><Trash2 size={15}/></button></div></footer></article>)}</div>}
      {!busy&&!visible.length&&<div className="empty"><Users size={28}/><p>No requirements match this view.</p></div>}
    </div>
    {newOpen&&createPortal(<div className="modal-backdrop centered-dialog" onMouseDown={()=>setNewOpen(false)}><div className="modal requirement-create-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">New workforce need</p><h2>Create Requirement</h2></div><button onClick={()=>setNewOpen(false)}><X size={18}/></button></div><div className="modal-body"><p className="modal-intro">Choose how the opening should be prepared. It stays private until you publish it.</p><div className="requirement-type-choice"><button className={target==="active"?"active":""} onClick={()=>setTarget("active")}><BriefcaseBusiness/><b>Regular requirement</b><span>Standard public opening</span></button><button className={target==="urgent"?"active urgent":""} onClick={()=>setTarget("urgent")}><AlertTriangle/><b>Urgent requirement</b><span>Priority card + homepage strip</span></button></div><div className="modal-actions"><button onClick={()=>setNewOpen(false)}>Cancel</button><button className="primary-button" disabled={creating} onClick={()=>void create()}>{creating?"Creating…":"Create & open editor"}</button></div></div></div></div>,document.body)}
    {editing&&<RequirementEditor item={editing} onClose={()=>setEditing(null)} onSaved={()=>{load();}}/>}
  </section>;
}

function RequirementEditor({item,onClose,onSaved}:{item:RequirementItem;onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState<Form|null>(null), [tab,setTab]=useState<typeof tabs[number][0]>("identity"), [loading,setLoading]=useState(true), [saving,setSaving]=useState<"draft"|"publish"|null>(null), [dirty,setDirty]=useState(false), [notice,setNotice]=useState(""), [apps,setApps]=useState(0);
  useEffect(()=>{api<EditorResponse>(`/cms/requirements/${item.id}/editor`).then(r=>{setForm({...r.data,documents:[...r.data.documents,...blankDoc].slice(0,6),contacts:[...r.data.contacts,blankContact,blankContact].slice(0,2)});setApps(r.application_count);setNotice(r.has_draft?"Draft restored. It is not public yet.":"Published data loaded.");}).catch(e=>setNotice(e instanceof Error?e.message:"Could not load editor.")).finally(()=>setLoading(false));},[item.id]);
  useEffect(()=>{document.body.classList.add("editor-open");return()=>document.body.classList.remove("editor-open");},[]);
  function update<K extends keyof Form>(key:K,value:Form[K]){setForm(current=>current?{...current,[key]:value}:current);setDirty(true);}
  function close(){if(!dirty||confirm("Close and discard unsaved changes?"))onClose();}
  async function save(mode:"draft"|"publish"){if(!form)return;setSaving(mode);setNotice("");const body={...form,documents:form.documents.filter(Boolean),contacts:form.contacts.filter(c=>c.raw.trim()).map(c=>({...c,raw:c.raw.replace(/[^0-9+]/g,"")})),opens_at:form.opens_at||null,closes_at:form.closes_at||null,rate_amount:form.rate_amount||null};try{await api(`/cms/requirements/${item.id}/${mode}`,{method:mode==="draft"?"PUT":"POST",body:JSON.stringify(body)});setDirty(false);setNotice(mode==="draft"?"Draft saved safely. It remains private.":form.status==="closed"?"Requirement closed. Existing applications remain available.":`Published as ${form.status}. Public site updated.`);onSaved();}catch(e){setNotice(e instanceof Error?e.message:"Could not save changes.");}finally{setSaving(null);}}
  if(typeof document==="undefined")return null;
  return createPortal(<div className="modal-backdrop project-editor-backdrop" onMouseDown={close}><section className="project-editor requirement-editor" onMouseDown={e=>e.stopPropagation()}><header className="project-editor-head"><div><p className="eyebrow">Requirement editor</p><h2>{form?.position||item.title||"New requirement"}</h2><span className={`badge badge-${item.status}`}>{item.status}</span><em>{apps} application{apps===1?"":"s"}</em>{dirty&&<em>Unsaved changes</em>}</div><div className="project-editor-actions"><button className="editor-draft-button" disabled={loading||!!saving} onClick={()=>void save("draft")}><Save size={16}/>Save draft</button><button className="primary-button compact" disabled={loading||!!saving} onClick={()=>void save("publish")}>{saving==="publish"?"Publishing…":form?.status==="closed"?"Save & close":"Publish"}</button><button className="editor-close" onClick={close}><X size={19}/></button></div></header><nav className="project-editor-tabs">{tabs.map(([id,name,Icon],i)=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{i+1}</span><Icon size={16}/>{name}</button>)}</nav>{loading||!form?<div className="project-editor-loading"><div className="skeleton"><i/><i/></div></div>:<div className="project-editor-content"><div className="project-editor-form"><div className="editor-section"><h3>{tabs.find(([id])=>id===tab)?.[1]}</h3><p>Fields map directly to the fixed public requirement card and application flow.</p></div>
    {tab==="identity"&&<><div className="editor-two-cols"><label>Position title<input value={form.position} onChange={e=>{update("position",e.target.value);if(item.status==="draft"&&(!form.code||form.code.startsWith("new-requirement-")))update("code",slugify(e.target.value));}}/></label><label>Public code<input value={form.code} onChange={e=>update("code",slugify(e.target.value))}/><small>Used by the public application link.</small></label><label>Project / client<input value={form.project_name} onChange={e=>update("project_name",e.target.value)}/></label><label>Location<input value={form.location} onChange={e=>update("location",e.target.value)}/></label></div><label>Approval / credential<input value={form.approval} onChange={e=>update("approval",e.target.value)} placeholder="Aramco Approved"/></label><label>Short role description<textarea rows={4} value={form.description} onChange={e=>update("description",e.target.value)}/></label></>}
    {tab==="offer"&&<><div className="editor-two-cols"><label>Required headcount<input type="number" min="1" value={form.headcount} onChange={e=>update("headcount",Math.max(1,Number(e.target.value)))}/></label><label>Duration<input value={form.duration} onChange={e=>update("duration",e.target.value)} placeholder="Long Term"/></label><label>Rate amount<input type="number" min="0" step="0.01" value={form.rate_amount||""} onChange={e=>update("rate_amount",e.target.value||null)}/></label><label>Rate unit<input value={form.rate_unit} onChange={e=>update("rate_unit",e.target.value)} placeholder="hour"/></label><label>Currency<input maxLength={3} value={form.rate_currency} onChange={e=>update("rate_currency",e.target.value.toUpperCase())}/></label><label>Salary cycle<input value={form.salary_cycle} onChange={e=>update("salary_cycle",e.target.value)}/></label><label>Food<input value={form.food} onChange={e=>update("food",e.target.value)}/></label><label>Accommodation<input value={form.accommodation} onChange={e=>update("accommodation",e.target.value)}/></label></div></>}
    {tab==="apply"&&<><section className="fixed-public-fields"><div><h4>Required documents</h4><p>Up to six documents shown on the public card.</p></div>{form.documents.map((value,i)=><label key={i}>Document {i+1}<input value={value} onChange={e=>{const rows=[...form.documents];rows[i]=e.target.value;update("documents",rows);}} placeholder={i===0?"Valid Iqama":"Medical Insurance"}/></label>)}</section><section className="fixed-public-fields"><div><h4>Application contacts</h4><p>Up to two verified public contact numbers.</p></div>{form.contacts.map((contact,i)=><div className="requirement-contact-fields" key={i}><label>Display number<input value={contact.display} onChange={e=>{const rows=[...form.contacts];rows[i]={...contact,display:e.target.value};update("contacts",rows);}} placeholder="+966 55 000 0000"/></label><label>WhatsApp / E.164 digits<input value={contact.raw} onChange={e=>{const rows=[...form.contacts];rows[i]={...contact,raw:e.target.value};update("contacts",rows);}} placeholder="966550000000"/></label><label className="editor-toggle"><input type="checkbox" checked={contact.whatsapp} onChange={e=>{const rows=[...form.contacts];rows[i]={...contact,whatsapp:e.target.checked};update("contacts",rows);}}/><span><b>WhatsApp enabled</b></span></label></div>)}</section></>}
    {tab==="publish"&&<><div className="editor-two-cols"><label>Opening date<input type="datetime-local" value={isoLocal(form.opens_at)} onChange={e=>update("opens_at",e.target.value||null)}/></label><label>Closing date<input type="datetime-local" value={isoLocal(form.closes_at)} onChange={e=>update("closes_at",e.target.value||null)}/></label></div><div className="requirement-status-choice">{(["active","urgent","closed"] as const).map(s=><button key={s} className={form.status===s?`active ${s}`:""} onClick={()=>update("status",s)}><b>{label(s)}</b><span>{s==="active"?"Visible on Requirements page":s==="urgent"?"Priority + homepage strip":"Hidden from public; history retained"}</span>{form.status===s&&<Check size={16}/>}</button>)}</div></>}
  </div><aside className="project-editor-preview"><span>Live public card preview</span><div className={`requirement-live-card ${form.status}`}><div><small>{form.status}</small><b>{form.approval||"Verified opening"}</b></div><p>{form.project_name||"Project name"}</p><h2>{form.position||"Position title"}</h2><div className="requirement-live-grid"><span><Users/>Required<strong>{form.headcount}</strong></span><span><CircleDollarSign/>Rate<strong>{form.rate_amount?`${form.rate_amount} ${form.rate_currency} / ${form.rate_unit}`:"TBD"}</strong></span></div><ul><li><MapPin/>{form.location||"Saudi Arabia"}</li><li><CalendarClock/>{form.duration||"Duration to be confirmed"}</li><li><Phone/>{form.contacts.find(c=>c.raw)?.display||"Application form enabled"}</li></ul><button>Apply now</button></div></aside></div>}<footer className="project-editor-foot"><p>{notice||"Changes are public only after Publish."}</p><div><button onClick={close}>Close</button><button className="editor-draft-button" disabled={loading||!!saving} onClick={()=>void save("draft")}>Save draft</button><button className="primary-button compact" disabled={loading||!!saving} onClick={()=>void save("publish")}>Publish</button></div></footer></section></div>,document.body);
}
