"use client";

import Image from "next/image";
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, Clock, Quote } from "lucide-react";
import { Link } from "@/components/nav/AppLink";
import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { NewsletterCTA } from "@/components/blog/NewsletterCTA";
import { BlogCard } from "@/components/blog/BlogCard";
import { ContentFaq } from "@/components/blog/ContentFaq";
import { useTranslatedPost, useTranslatedPosts } from "@/i18n/use-translated-blog";
import { useCmsContent } from "@/lib/cms-content";

export function BlogPostDetailView({ slug }: { slug: string }) {
  const { loading } = useCmsContent();
  const post = useTranslatedPost(slug);
  const { all } = useTranslatedPosts();
  if (!post) {
    if (loading) return <main className="min-h-screen bg-background" />;
    return <div className="min-h-screen bg-background"><Header /><main className="grid min-h-[65vh] place-items-center px-6 text-center"><div><h1 className="text-3xl font-bold text-navy">Article not found.</h1><Link to="/blog" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-gold"><ArrowLeft className="h-4 w-4" />Back to all articles</Link></div></main><Footer /></div>;
  }
  const related = all.filter((item) => item.slug !== post.slug).slice(0, 3);
  return <div className="min-h-screen bg-background"><Header /><main>
    <section className="relative overflow-hidden bg-navy-deep py-28 text-white lg:py-32"><Image src={post.image} alt="" fill priority sizes="100vw" className="object-cover opacity-20" /><div className="absolute inset-0 bg-gradient-to-b from-navy-deep/70 via-navy-deep/90 to-navy-deep" /><div className="container-wide relative grid items-end gap-10 lg:grid-cols-12"><div className="lg:col-span-8"><Link to="/blog" className="mb-7 inline-flex items-center gap-2 text-sm text-white/65 hover:text-gold"><ArrowLeft className="h-4 w-4" />Back to all articles</Link><span className="block w-fit rounded-full bg-gold px-3 py-1 text-[10px] font-bold uppercase tracking-[0.2em] text-navy">{post.category}</span><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-[1.06] md:text-5xl lg:text-6xl">{post.title}</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-white/70 md:text-lg">{post.excerpt}</p></div><aside className="border-t border-white/15 pt-5 lg:col-span-4 lg:border-l lg:border-t-0 lg:pl-7 lg:pt-0"><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-gold">Article details</div><div className="mt-4 grid gap-3 text-sm text-white/70"><span className="inline-flex items-center gap-2"><CalendarDays className="h-4 w-4 text-gold" />{post.date}</span><span className="inline-flex items-center gap-2"><Clock className="h-4 w-4 text-gold" />{post.readMins} min read</span><span>{post.author}</span><span className="text-white/45">{post.authorRole}</span></div></aside></div></section>
    <section className="border-b border-border bg-white"><div className="container-wide grid gap-0 lg:grid-cols-12"><div className="relative aspect-[16/8] overflow-hidden lg:col-span-8"><Image src={post.image} alt={post.title} fill sizes="(max-width: 1024px) 100vw, 70vw" className="object-cover" /></div><div className="flex items-center border-border bg-sand-soft p-7 lg:col-span-4 lg:border-l lg:p-9"><p className="text-lg font-semibold leading-relaxed text-navy">A NOVARISE field perspective for project leaders, procurement teams and delivery partners.</p></div></div></section>
    <section className="bg-background py-16 lg:py-20"><div className="container-wide grid gap-10 lg:grid-cols-12"><article className="lg:col-span-8"><div className="space-y-6 text-base leading-[1.85] text-muted-foreground md:text-lg">{post.paragraphs.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div>{post.pullQuote && <blockquote className="relative my-10 overflow-hidden rounded-2xl bg-navy p-7 text-white md:p-8"><Quote className="absolute right-6 top-5 h-14 w-14 text-gold/15" /><p className="relative text-xl font-semibold leading-relaxed">“{post.pullQuote}”</p></blockquote>}<div className="mt-10 flex items-center gap-4 border-t border-border pt-7"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-gold/15 text-lg font-bold text-gold">{post.author.charAt(0)}</div><div><div className="font-semibold text-navy">{post.author}</div><div className="mt-1 text-xs uppercase tracking-[0.18em] text-muted-foreground">{post.authorRole}</div></div></div></article><aside className="lg:col-span-4"><div className="rounded-2xl border border-border bg-sand-soft p-6"><div className="text-xs font-bold uppercase tracking-[0.22em] text-gold">Key takeaways</div><ul className="mt-5 space-y-4">{post.keyTakeaways.map((item) => <li key={item} className="flex gap-3 text-sm font-semibold leading-relaxed text-navy"><span className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gold/15 text-gold"><Check className="h-3.5 w-3.5" /></span>{item}</li>)}</ul></div></aside></div></section>
    {related.length > 0 && <section className="border-t border-border bg-sand-soft py-16 lg:py-20"><div className="container-wide"><div className="mb-8 flex items-end justify-between"><div><div className="eyebrow mb-2">Continue reading</div><h2 className="text-3xl font-bold text-navy">More from Insights</h2></div><Link to="/blog" className="hidden items-center gap-2 text-sm font-semibold text-navy hover:text-gold md:inline-flex">All articles <ArrowUpRight className="h-4 w-4" /></Link></div><div className="grid gap-6 md:grid-cols-3">{related.map((item) => <BlogCard key={item.slug} post={item} compact />)}</div></div></section>}
    <ContentFaq eyebrow="Article help" title="Reading & sharing." description="Useful answers for readers who want to follow or discuss this insight." items={[{ question: "Can I share this article with my team?", answer: "Yes. Every article has a public URL and can be shared directly with project and procurement teams." }, { question: "Where can I find more related stories?", answer: "Use the related articles above or visit the complete NOVARISE Insights archive." }]} />
    <NewsletterCTA />
  </main><Footer /></div>;
}
