"use client";

import Image from "next/image";
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, Clock3, MapPin } from "lucide-react";
import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { Link } from "@/components/nav/AppLink";
import { EventCard } from "@/components/blog/EventCard";
import { NewsletterCTA } from "@/components/blog/NewsletterCTA";
import { ContentFaq } from "@/components/blog/ContentFaq";
import { useTranslatedEvent, useTranslatedEvents } from "@/i18n/use-translated-blog";
import { useCmsContent } from "@/lib/cms-content";

export function EventDetailView({ slug }: { slug: string }) {
  const { loading } = useCmsContent();
  const event = useTranslatedEvent(slug);
  const all = useTranslatedEvents();
  if (!event) {
    if (loading) return <main className="min-h-screen bg-background" />;
    return <div className="min-h-screen bg-background"><Header /><main className="grid min-h-[65vh] place-items-center px-6 text-center"><div><h1 className="text-3xl font-bold text-navy">Event not found.</h1><Link to="/events" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-gold"><ArrowLeft className="h-4 w-4" />Back to events</Link></div></main><Footer /></div>;
  }
  const related = all.filter((item) => item.slug !== event.slug).sort((a, b) => Number(b.status === "Upcoming") - Number(a.status === "Upcoming")).slice(0, 3);
  const past = event.status === "Past";
  return <div className="min-h-screen bg-background"><Header /><main>
    <section className="relative overflow-hidden bg-navy-deep py-28 text-white lg:py-32"><Image src={event.image} alt="" fill priority sizes="100vw" className="object-cover opacity-25" /><div className="absolute inset-0 bg-gradient-to-b from-navy-deep/70 via-navy-deep/90 to-navy-deep" /><div className="container-wide relative grid items-end gap-10 lg:grid-cols-12"><div className="lg:col-span-8"><Link to="/events" className="mb-7 inline-flex items-center gap-2 text-sm text-white/65 hover:text-gold"><ArrowLeft className="h-4 w-4" />Back to all events</Link><div className="flex flex-wrap gap-2"><span className="rounded-full bg-gold px-3 py-1 text-[10px] font-bold uppercase tracking-[0.2em] text-navy">{event.type}</span><span className="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.2em]">{event.status}</span></div><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-[1.05] md:text-5xl lg:text-6xl">{event.title}</h1><p className="mt-5 max-w-3xl text-base leading-relaxed text-white/70 md:text-lg">{event.description}</p></div><aside className="border-t border-white/15 pt-5 lg:col-span-4 lg:border-l lg:border-t-0 lg:pl-7 lg:pt-0"><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-gold">At a glance</div><div className="mt-4 grid gap-3 text-sm text-white/70"><span className="inline-flex items-center gap-2"><CalendarDays className="h-4 w-4 text-gold" />{event.date}</span><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4 text-gold" />{event.time}</span><span className="inline-flex items-center gap-2"><MapPin className="h-4 w-4 text-gold" />{event.location}</span></div></aside></div></section>
    <section className="border-b border-border bg-white"><div className="container-wide grid lg:grid-cols-12"><div className="relative aspect-[16/8] overflow-hidden lg:col-span-8"><Image src={event.image} alt={event.title} fill sizes="(max-width: 1024px) 100vw, 70vw" className="object-cover" /></div><aside className="flex flex-col justify-between bg-sand-soft p-7 lg:col-span-4 lg:border-l lg:border-border lg:p-8"><div><div className="text-[10px] font-bold uppercase tracking-[0.22em] text-gold">Event information</div><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Venue</dt><dd className="mt-1 font-semibold text-navy">{event.venue}</dd></div><div><dt className="text-xs uppercase tracking-wider text-muted-foreground">Format</dt><dd className="mt-1 font-semibold text-navy">{event.type} · {event.status}</dd></div></dl></div><Link to="/contact" className="mt-7 inline-flex items-center justify-center gap-2 rounded-full bg-navy px-5 py-3 text-sm font-semibold text-white">{past ? "Discuss this event" : "Request a meeting"}<ArrowUpRight className="h-4 w-4 text-gold" /></Link></aside></div></section>
    <section className="bg-background py-16 lg:py-20"><div className="container-wide grid gap-10 lg:grid-cols-12"><article className="lg:col-span-8"><div className="eyebrow mb-4">Event overview</div><h2 className="text-3xl font-bold text-navy">Why this engagement matters.</h2><div className="mt-6 space-y-5 text-base leading-[1.85] text-muted-foreground md:text-lg">{event.overview.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><div className="mt-10"><div className="eyebrow mb-4">Programme</div><h2 className="text-3xl font-bold text-navy">Event agenda.</h2><div className="mt-6 divide-y divide-border border-y border-border">{event.agenda.map((item, index) => <div key={`${item.time}-${index}`} className="grid gap-3 py-5 sm:grid-cols-[110px_1fr]"><span className="text-sm font-bold text-gold">{item.time}</span><div><h3 className="font-bold text-navy">{item.title}</h3><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{item.description}</p></div></div>)}</div></div></article><aside className="lg:col-span-4"><div className="rounded-2xl border border-border bg-sand-soft p-6"><div className="text-xs font-bold uppercase tracking-[0.22em] text-gold">What to expect</div><h2 className="mt-3 text-2xl font-bold text-navy">Key takeaways.</h2><ul className="mt-6 space-y-4">{event.takeaways.map((item) => <li key={item} className="flex gap-3 text-sm font-semibold leading-relaxed text-navy"><span className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gold/15 text-gold"><Check className="h-3.5 w-3.5" /></span>{item}</li>)}</ul><Link to="/contact" className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-full border border-navy/15 bg-white px-4 py-3 text-sm font-semibold text-navy hover:border-gold hover:text-gold">{past ? "Talk to our team" : "Request a meeting"}<ArrowUpRight className="h-4 w-4" /></Link></div></aside></div></section>
    {related.length > 0 && <section className="border-t border-border bg-sand-soft py-16 lg:py-20"><div className="container-wide"><div className="mb-8 flex items-end justify-between"><div><div className="eyebrow mb-2">Continue exploring</div><h2 className="text-3xl font-bold text-navy">More events</h2></div><Link to="/events" className="hidden items-center gap-2 text-sm font-semibold text-navy hover:text-gold md:inline-flex">All events <ArrowUpRight className="h-4 w-4" /></Link></div><div className="grid gap-6 md:grid-cols-3">{related.map((item) => <EventCard key={item.slug} event={item} />)}</div></div></section>}
    <ContentFaq eyebrow="Event help" title="Before you attend." description="Answers for arranging a meeting, following an event and keeping up with future NOVARISE engagements." items={[{ question: "How do I arrange a meeting with NOVARISE?", answer: "Use the meeting request button above and our team will respond with the best available time and contact point." }, { question: "Where can I find previous event recaps?", answer: "All previous engagements remain available in the NOVARISE Events archive after their event date." }]} />
    <NewsletterCTA />
  </main><Footer /></div>;
}
