"""Add NovaFin sales, purchasing, banking, accounting, HR and admin tables

Revision ID: 20260930_0020
Revises: 20260929_0019
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260930_0020'
down_revision: str | None = '20260929_0019'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novafin_accounts',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_accounts_code')
    )
    op.create_table('novafin_assets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('depreciation_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_banks',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('branch', sa.String(length=150), nullable=True),
    sa.Column('account_no', sa.String(length=60), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_branches',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_capital_moves',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('move_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_capital_moves_code')
    )
    op.create_index(op.f('ix_novafin_capital_moves_code'), 'novafin_capital_moves', ['code'], unique=False)
    op.create_table('novafin_cash_moves',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('move_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_cash_moves_code')
    )
    op.create_index(op.f('ix_novafin_cash_moves_code'), 'novafin_cash_moves', ['code'], unique=False)
    op.create_table('novafin_contras',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('contra_date', sa.Date(), nullable=False),
    sa.Column('from_method', sa.String(length=60), nullable=False),
    sa.Column('to_method', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_contras_code')
    )
    op.create_index(op.f('ix_novafin_contras_code'), 'novafin_contras', ['code'], unique=False)
    op.create_table('novafin_departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_designations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_expense_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_fiscal_years',
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_income_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_journal_vouchers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_journal_vouchers_code')
    )
    op.create_index(op.f('ix_novafin_journal_vouchers_code'), 'novafin_journal_vouchers', ['code'], unique=False)
    op.create_table('novafin_rfqs',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('rfq_date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('vendor_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_rfqs_code')
    )
    op.create_index(op.f('ix_novafin_rfqs_code'), 'novafin_rfqs', ['code'], unique=False)
    op.create_table('novafin_cheques',
    sa.Column('cheque_no', sa.String(length=60), nullable=False),
    sa.Column('bank_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('party_name', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('cheque_date', sa.Date(), nullable=False),
    sa.Column('is_reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['novafin_banks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_credit_notes',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('note_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['novafin_customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_credit_notes_code')
    )
    op.create_index(op.f('ix_novafin_credit_notes_code'), 'novafin_credit_notes', ['code'], unique=False)
    op.create_table('novafin_employees',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('designation_id', sa.UUID(), nullable=True),
    sa.Column('basic_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['novafin_departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['designation_id'], ['novafin_designations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novafin_expense_vouchers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['novafin_expense_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_expense_vouchers_code')
    )
    op.create_index(op.f('ix_novafin_expense_vouchers_code'), 'novafin_expense_vouchers', ['code'], unique=False)
    op.create_table('novafin_income_vouchers',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('voucher_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['novafin_income_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_income_vouchers_code')
    )
    op.create_index(op.f('ix_novafin_income_vouchers_code'), 'novafin_income_vouchers', ['code'], unique=False)
    op.create_table('novafin_journal_voucher_lines',
    sa.Column('voucher_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['novafin_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['voucher_id'], ['novafin_journal_vouchers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_journal_voucher_lines_voucher_id'), 'novafin_journal_voucher_lines', ['voucher_id'], unique=False)
    op.create_table('novafin_purchase_orders',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['novafin_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_purchase_orders_code')
    )
    op.create_index(op.f('ix_novafin_purchase_orders_code'), 'novafin_purchase_orders', ['code'], unique=False)
    op.create_table('novafin_quotes',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['novafin_customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_quotes_code')
    )
    op.create_index(op.f('ix_novafin_quotes_code'), 'novafin_quotes', ['code'], unique=False)
    op.create_table('novafin_rfq_lines',
    sa.Column('rfq_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rfq_id'], ['novafin_rfqs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_rfq_lines_rfq_id'), 'novafin_rfq_lines', ['rfq_id'], unique=False)
    op.create_table('novafin_orders',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['novafin_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['novafin_quotes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_orders_code')
    )
    op.create_index(op.f('ix_novafin_orders_code'), 'novafin_orders', ['code'], unique=False)
    op.create_table('novafin_purchase_order_lines',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['novafin_purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_purchase_order_lines_purchase_order_id'), 'novafin_purchase_order_lines', ['purchase_order_id'], unique=False)
    op.create_table('novafin_purchase_returns',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('purchase_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['novafin_purchases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['novafin_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_purchase_returns_code')
    )
    op.create_index(op.f('ix_novafin_purchase_returns_code'), 'novafin_purchase_returns', ['code'], unique=False)
    op.create_table('novafin_quote_lines',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['novafin_quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_quote_lines_quote_id'), 'novafin_quote_lines', ['quote_id'], unique=False)
    op.create_table('novafin_salary_slips',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=20), nullable=False),
    sa.Column('basic', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('allowance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deduction', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['novafin_employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_salary_slips_code')
    )
    op.create_index(op.f('ix_novafin_salary_slips_code'), 'novafin_salary_slips', ['code'], unique=False)
    op.create_table('novafin_sales_returns',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['novafin_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['novafin_invoices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_sales_returns_code')
    )
    op.create_index(op.f('ix_novafin_sales_returns_code'), 'novafin_sales_returns', ['code'], unique=False)
    op.create_table('novafin_deliveries',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['novafin_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['novafin_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_novafin_deliveries_code')
    )
    op.create_index(op.f('ix_novafin_deliveries_code'), 'novafin_deliveries', ['code'], unique=False)
    op.create_table('novafin_order_lines',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['novafin_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_order_lines_order_id'), 'novafin_order_lines', ['order_id'], unique=False)
    op.create_table('novafin_purchase_return_lines',
    sa.Column('purchase_return_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['novafin_purchase_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_purchase_return_lines_purchase_return_id'), 'novafin_purchase_return_lines', ['purchase_return_id'], unique=False)
    op.create_table('novafin_sales_return_lines',
    sa.Column('sales_return_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_return_id'], ['novafin_sales_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_sales_return_lines_sales_return_id'), 'novafin_sales_return_lines', ['sales_return_id'], unique=False)
    op.create_table('novafin_delivery_lines',
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['novafin_deliveries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['novafin_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novafin_delivery_lines_delivery_id'), 'novafin_delivery_lines', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novafin_delivery_lines_delivery_id'), table_name='novafin_delivery_lines')
    op.drop_table('novafin_delivery_lines')
    op.drop_index(op.f('ix_novafin_sales_return_lines_sales_return_id'), table_name='novafin_sales_return_lines')
    op.drop_table('novafin_sales_return_lines')
    op.drop_index(op.f('ix_novafin_purchase_return_lines_purchase_return_id'), table_name='novafin_purchase_return_lines')
    op.drop_table('novafin_purchase_return_lines')
    op.drop_index(op.f('ix_novafin_order_lines_order_id'), table_name='novafin_order_lines')
    op.drop_table('novafin_order_lines')
    op.drop_index(op.f('ix_novafin_deliveries_code'), table_name='novafin_deliveries')
    op.drop_table('novafin_deliveries')
    op.drop_index(op.f('ix_novafin_sales_returns_code'), table_name='novafin_sales_returns')
    op.drop_table('novafin_sales_returns')
    op.drop_index(op.f('ix_novafin_salary_slips_code'), table_name='novafin_salary_slips')
    op.drop_table('novafin_salary_slips')
    op.drop_index(op.f('ix_novafin_quote_lines_quote_id'), table_name='novafin_quote_lines')
    op.drop_table('novafin_quote_lines')
    op.drop_index(op.f('ix_novafin_purchase_returns_code'), table_name='novafin_purchase_returns')
    op.drop_table('novafin_purchase_returns')
    op.drop_index(op.f('ix_novafin_purchase_order_lines_purchase_order_id'), table_name='novafin_purchase_order_lines')
    op.drop_table('novafin_purchase_order_lines')
    op.drop_index(op.f('ix_novafin_orders_code'), table_name='novafin_orders')
    op.drop_table('novafin_orders')
    op.drop_index(op.f('ix_novafin_rfq_lines_rfq_id'), table_name='novafin_rfq_lines')
    op.drop_table('novafin_rfq_lines')
    op.drop_index(op.f('ix_novafin_quotes_code'), table_name='novafin_quotes')
    op.drop_table('novafin_quotes')
    op.drop_index(op.f('ix_novafin_purchase_orders_code'), table_name='novafin_purchase_orders')
    op.drop_table('novafin_purchase_orders')
    op.drop_index(op.f('ix_novafin_journal_voucher_lines_voucher_id'), table_name='novafin_journal_voucher_lines')
    op.drop_table('novafin_journal_voucher_lines')
    op.drop_index(op.f('ix_novafin_income_vouchers_code'), table_name='novafin_income_vouchers')
    op.drop_table('novafin_income_vouchers')
    op.drop_index(op.f('ix_novafin_expense_vouchers_code'), table_name='novafin_expense_vouchers')
    op.drop_table('novafin_expense_vouchers')
    op.drop_table('novafin_employees')
    op.drop_index(op.f('ix_novafin_credit_notes_code'), table_name='novafin_credit_notes')
    op.drop_table('novafin_credit_notes')
    op.drop_table('novafin_cheques')
    op.drop_index(op.f('ix_novafin_rfqs_code'), table_name='novafin_rfqs')
    op.drop_table('novafin_rfqs')
    op.drop_index(op.f('ix_novafin_journal_vouchers_code'), table_name='novafin_journal_vouchers')
    op.drop_table('novafin_journal_vouchers')
    op.drop_table('novafin_income_categories')
    op.drop_table('novafin_fiscal_years')
    op.drop_table('novafin_expense_categories')
    op.drop_table('novafin_designations')
    op.drop_table('novafin_departments')
    op.drop_index(op.f('ix_novafin_contras_code'), table_name='novafin_contras')
    op.drop_table('novafin_contras')
    op.drop_index(op.f('ix_novafin_cash_moves_code'), table_name='novafin_cash_moves')
    op.drop_table('novafin_cash_moves')
    op.drop_index(op.f('ix_novafin_capital_moves_code'), table_name='novafin_capital_moves')
    op.drop_table('novafin_capital_moves')
    op.drop_table('novafin_branches')
    op.drop_table('novafin_banks')
    op.drop_table('novafin_assets')
    op.drop_table('novafin_accounts')
    # ### end Alembic commands ###
